name: Ensure Version Increment

on:
  pull_request:
    branches:
      - master

jobs:
  check-version:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [ Backend, Frontend]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch master branch
        run: git fetch origin master

      - name: Get current and base version
        id: versions
        run: |
          CURRENT_VERSION=$(jq -r .version ${{ matrix.package }}/package.json)
          BASE_VERSION=$(git show origin/master:${{ matrix.package }}/package.json | jq -r .version)
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
          echo "BASE_VERSION=$BASE_VERSION" >> $GITHUB_ENV

      - name: Check for changes in ${{ matrix.package }}
        run: |
          CHANGED=$(git diff --name-only origin/master HEAD -- ${{ matrix.package }}/)
          if [[ -n "$CHANGED" ]]; then
            echo "CHANGED=true" >> $GITHUB_ENV
          else
            echo "CHANGED=false" >> $GITHUB_ENV
          fi

      - name: Compare versions if changed
        run: |
          is_greater() {
            dpkg --compare-versions "$1" "gt" "$2"
          }

          if [[ "$CHANGED" == "true" ]]; then
            if ! is_greater "$CURRENT_VERSION" "$BASE_VERSION"; then
              echo "${{ matrix.package }} version must be incremented. Current: $CURRENT_VERSION, Base: $BASE_VERSION"
              exit 1
            else
              echo "${{ matrix.package }} version increment verified."
            fi
          else
            echo "No changes detected in ${{ matrix.package }}. Skipping version check."
          fi
